### ISSUE TITLE
System.Management.ManagementException: Generic failure

### ISSUE THREAD

**Issue by iyaso** [winsw/winsw#204]
I've installed and started my service on my PC without problems, but when I try to install the service on the server, I got this exception:
```
2017-04-12 10:53:54,904 INFO  - Starting ServiceWrapper in the CLI mode
2017-04-12 10:53:55,366 FATAL - Unhandled exception
System.Management.ManagementException: Generic failure
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Select(String )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
System.Management.ManagementException: Generic failure
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Select(String )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```

**Comment by oleg-nenashev** [comment]
According to [this article](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c98465fe-c40f-4d1f-9654-316e2888069c/systemmanagement-generic-failure?forum=netfxbcl), it may happen if the WMI service is not running. Could you please check it?
