### ISSUE TITLE
How is the Service User used?

### ISSUE THREAD

**Issue by isaacgainey-wsc** [winsw/winsw#258]
Good Morning,

I have an inquiry about which user is calling java. The documentation leads me to believe that it's the service's "Log on as" account. However, I when start a Spring boot application as a service and its first console line is `example.SpringBootApplication : Starting SpringBoootApplication v0.0.1 on [local machine name] with PID 9052 (C:\SpringBootApp\springbootapp-0.0.1\lib\springbootapp-0.0.1.jar started by [local machine name] in C:\SpringBootApp\springbootapp-0.0.1)`. 
[local machine name] does contain a $ at the end of it.
This wouldn't be a concern, however, there are multiple database connections with usernames and passwords. And only as a service, the error log appears for each sqlserver `com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '[local machine name]'. ClientConnectionId:[id]`, and other databases have invalid user and pass error messages.

My starting xml file was
```
 <serviceaccount>
    <domain>domain</domain>
     <user>user</user>
     <password>pass</password>
 </serviceaccount>
```
I've altered it to hard code to Down-Level Logon Name
```
 <serviceaccount>
     <user>domain\user</user>
     <password>pass</password>
 </serviceaccount>
```
and to User Principal Name
```
 <serviceaccount>
     <user>user@domain</user>
     <password>pass</password>
 </serviceaccount>
```
with the same results.

Here is the full current xml file.
```
<service>
	<id>@dist.project.id@</id>
	<name>@dist.project.name@</name>
	<description>@dist.project.description@</description>
	<workingdirectory>%BASE%\</workingdirectory>
	<logpath>%BASE%\logs</logpath>
	<logmode>reset</logmode>
	<startmode>manual</startmode>
	<priority>abovenormal</priority>

	<executable>java</executable>

	<startargument>-Dspring.application.admin.enabled=true</startargument>
	<startargument>-Dcom.sun.management.jmxremote.port=@dist.jmx.port@</startargument>
	<startargument>-Dcom.sun.management.jmxremote.authenticate=false</startargument>
	<startargument>-Dcom.sun.management.jmxremote.ssl=false</startargument>
	<startargument>-jar</startargument>
	<startargument>-Dloader.main=@dist.start.class@</startargument>

	<stopexecutable>java</stopexecutable>
	<stopargument>-jar</stopargument>
	<stopargument>-Dloader.main=@dist.stop.class@</stopargument>
	<stopargument>@dist.jmx.port@</stopargument>

	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="none" />
	<resetfailure>1 hour</resetfailure>
    
 	<serviceaccount>
		<domain>domain</domain>
		<user>user</user>
		<password>pass</password>
	</serviceaccount>
</service>
```

**Comment by oleg-nenashev** [comment]
`serviceaccount` changes get applied only when you reinstall the service. If you just restart it, the old settings will be used

**Comment by isaacgainey-wsc** [comment]
Both install and uninstall arguments were used in between updating the xml. I've also opened window's Services and manually entered the login information.

**Comment by NextTurn** [comment]
This issue is not in `<serviceaccount>`. But SQL Server login really failed.

**Comment by NextTurn** [comment]
```xml
<service>
  <id>{id}</id>
  <name>{name}</name>
  <description>{description}</description>
  <executable>{executable}</executable>
  <!-- <serviceaccount>
    <domain>.</domain>
    <user>{user}</user>
    <password>{password}</password>
  </serviceaccount> -->
</service>
```

## Microsoft SqlClient Data Provider for SQL Server

```cs
using System;
using System.Data.SqlClient;

class Program
{
    static void Main()
    {
        var builder = new SqlConnectionStringBuilder { IntegratedSecurity = true };
        using var connection = new SqlConnection(builder.ConnectionString);
        connection.Open();
        Console.WriteLine(connection.State);
        using var command = new SqlCommand("USE SampleDB; SELECT Id FROM SampleTable;", connection);
        Console.WriteLine(command.ExecuteScalar());
    }
}
```

### Authenticated user access succeeded

```
Open
42
```

### Unauthenticated user access failed

```
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): The server principal "NT AUTHORITY\SYSTEM" is not able to access the database "SampleDB" under the current security context.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Program.Main()
ClientConnectionId:513dab0a-454c-4b6c-91a7-a3f380841ad9
Error Number:916,State:2,Class:14
```

## Microsoft ODBC Driver 17 for SQL Server

```cs
using System;
using System.Data.Odbc;

class Program
{
    static void Main()
    {
        var builder = new OdbcConnectionStringBuilder { Dsn = "DS" };
        using var connection = new OdbcConnection(builder.ConnectionString);
        connection.Open();
        Console.WriteLine(connection.State);
        using var command = new OdbcCommand("USE SampleDB; SELECT Id FROM SampleTable;", connection);
        Console.WriteLine(command.ExecuteScalar());
    }
}
```

### Authenticated user access succeeded

```
Open
42
```

### Unauthenticated user access failed

```
Unhandled exception. System.Data.Odbc.OdbcException (0x80131937): ERROR [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'NT AUTHORITY\SYSTEM'.
ERROR [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "SampleDB" requested by the login. The login failed.
ERROR [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'NT AUTHORITY\SYSTEM'.
ERROR [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "SampleDB" requested by the login. The login failed.
   at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode)
   at System.Data.Odbc.OdbcConnectionHandle..ctor(OdbcConnection connection, OdbcConnectionString constr, OdbcEnvironmentHandle environmentHandle)
   at System.Data.Odbc.OdbcConnectionOpen..ctor(OdbcConnection outerConnection, OdbcConnectionString connectionOptions)
   at System.Data.Odbc.OdbcConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.Odbc.OdbcConnection.Open()
   at Program.Main()
```

---

Re-closing as non-reproducible.
