### ISSUE TITLE
Child processes won't be terminated and service was stop with exit code 0

### ISSUE THREAD

**Issue by krikil86** [winsw/winsw#328]
When computer restart, Child processes won't be terminated and service was stop with exit code 0. When the computer turns on again service not start.

2019-07-18 21:50:32,765 INFO  - Starting C:\Program Files\sinkron kace\sinkron_kace.exe 
2019-07-18 21:50:35,046 INFO  - Started process 4592
2019-07-18 21:50:35,093 DEBUG - Forwarding logs of the process System.Diagnostics.Process (sinkron_kace) to winsw.DefaultLogAppender
2019-07-18 22:16:13,593 INFO  - Stopping sinkron_kace
2019-07-18 22:16:13,734 DEBUG - ProcessKill 4592
2019-07-18 22:16:23,734 WARN  - Failed to locate children of the process with PID=4592. **Child processes won't be terminated**
System.Runtime.InteropServices.COMException (0x8007045B): A system shutdown is in progress. (Exception from HRESULT: 0x8007045B)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at winsw.Util.ProcessHelper.GetChildPids(Int32 pid)
2019-07-18 22:16:24,421 INFO  - Stopping process 4592
2019-07-18 22:16:24,421 INFO  - Send SIGINT 4592
2019-07-18 22:16:24,468 WARN  - SIGINT to 4592 failed - Killing as fallback
2019-07-18 22:16:24,671 INFO  - Finished sinkron_kace
2019-07-18 22:16:24,718 DEBUG - Completed. **Exit code is 0**

How to solve this problem?

**Comment by NextTurn** [comment]
> A system shutdown is in progress.

We can't depend on the WMI service when the system is shutting down, just as we can't use Event Log.

https://github.com/winsw/winsw/blob/b0c09e1bb1a3edfa8cb6671892a48564c13e3562/src/Core/ServiceWrapper/Main.cs#L156

**Comment by yj993549741** [comment]
I have a so problem

**Comment by NextTurn** [comment]
Fixed in v3. Feel free to backport.
