### ISSUE TITLE
Regression: 2.10.1:  Error when starting the service

### ISSUE THREAD

**Issue by felfert** [winsw/winsw#662]
**Summary**. I just tried version 2.10.1 which fixes #659 (service installs fine), but fails to start the service subsequently with the following error in windows event log

## Steps to reproduce
See #659 

The error logged in the event log:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='jenkins'/><EventID Qualifiers='0'>0</EventID><Level>2</Level><Task>0</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2020-08-25T11:11:45.779939800Z'/><EventRecordID>2057</EventRecordID><Channel>Application</Channel><Computer>bh-w2016-18</Computer><Security/></System><EventData><Data>Service cannot be started. WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension ---&gt; WinSW.Extensions.ExtensionException: killOnStartup: Class winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensionFromXml(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)</Data></EventData><RenderingInfo Culture='en-US'><Message>Service cannot be started. WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension ---&gt; WinSW.Extensions.ExtensionException: killOnStartup: Class winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensionFromXml(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)</Message><Level>Error</Level><Task></Task><Opcode>Info</Opcode><Channel></Channel><Provider></Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event></Events>
```

## Environment

* WinSW version: 2.10.1
* WinSW package type: nuget
* Windows version: any
* Wrapped executable and version: java

**Comment by oleg-nenashev** [comment]
@felfert please use `WinSW.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension`, not `winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension`. Due whatever reason, class search became case sentsitive

**Comment by oleg-nenashev** [comment]
Sorry for the delay, the release is out: https://github.com/winsw/winsw/releases/tag/v2.10.2

**Comment by NextTurn** [comment]
`winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension` should still be used as documented.

**Comment by felfert** [comment]
No problem. We are simply using the old version for now. Will test and give feedback after my vacation in ~ 3weeks

Am 31. August 2020 17:20:17 WESZ schrieb Oleg Nenashev <notifications@github.com>:
>Sorry for the delay, the release is out:
>https://github.com/winsw/winsw/releases/tag/v2.10.2
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/winsw/winsw/issues/662#issuecomment-683882131

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by harryssuperman** [comment]
In my case i had no .NET Framework installed, but after following the Microsoft [site ](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#query-the-registry-using-powershell) to check which version ist installed, i could check my version was in a Powershell .NET Framework Version: 4.8.1 or later and after changing some of the extension class names i've got the right for me was: winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension
