### ISSUE TITLE
Installation fails with Unhandled exception

### ISSUE THREAD

**Issue by jakubgs** [winsw/winsw#687]
## Summary

I'm trying to run the Jenkins Agent using WinSW but it randomly fails with:
```
10:17:11,483 - Installing service 'Jenkins Agent (JenkinsAgent)'...
10:17:11,540 - Unhandled exception
10:17:11,873 - Unhandled exception
10:17:12,148 - Unhandled exception
```

## Steps to reproduce

```xml
<service>
  <id>JenkinsAgent</id>
  <name>Jenkins Agent</name>
  <description>This service runs an agent for Jenkins automation server.</description>
  <executable>java.exe</executable>
  <arguments>-Xrs -jar C:\Users\jenkins\JenkinsService.jar -jnlpUrl https://ci.status.im/computer/windows-01/slave-agent.jnlp -secret MyJenkinsSecret -workDir C:\Users\jenkins\workspace</arguments>
  <workingdirectory>C:\Users\jenkins</workingdirectory>
  <env name="PATH" value="C:\Program Files\PowerShell\7;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\OpenSSH\;C:\ProgramData\scoop\apps\openjdk\current\bin;C:\ProgramData\scoop\apps\gcc\current\bin;C:\ProgramData\scoop\apps\git\current\bin;C:\ProgramData\scoop\apps\git\current\usr\bin;C:\ProgramData\scoop\shims" />
  <logmode>rotate</logmode>
  <onfailure action="restart" />
  <delayedAutoStart/>
  <serviceaccount>
    <user>jenkins</user>
    <password>MySecretPassword</password>
  </serviceaccount>
</service>
```

## Environment

* WinSW version: `3.0.0-alpha.4`
* WinSW package type: `NET461`
* Windows version: `Microsoft Windows Server Datacenter` `10.0.19041 N/A Build 19041`
* Wrapped executable and version: Jenkins Agent `4.5` from Jenkins `2.257`

## Thoughts

I've tried using the stable `2.10.2` but that just fails every time.
I'm trying to understand what I'm supposed to do to get more info about what's the exception. I'm happy to help debug this.

**Comment by jakubgs** [comment]
Just for the record, if I try to use `2.10.2` it fails every time with:
```
2020-09-24 18:56:30,550 INFO  - Starting the service with id 'JenkinsAgent'
2020-09-24 18:56:30,637 FATAL - WMI Operation failure: ServiceLogonFailure
WMI.WmiException: ServiceLogonFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] arguments)
   at WinSW.Program.<Run>g__Start|2_2(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
WMI.WmiException: ServiceLogonFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] arguments)
   at WinSW.Program.<Run>g__Start|2_2(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
```
At least with the `3.0.0-alpha.4` it works half the time. And this is on a host created from the same image on Google Cloud.

**Comment by oleg-nenashev** [comment]
Please check the Application event log in your Windows system. There might
be a stacktrace.

If not, it is also a diagnosability bug.

**Comment by NextTurn** [comment]
https://github.com/winsw/winsw/blob/v3.0.0-alpha.4/docs/migrate-to-3-x.md

> Just for the record, if I try to use `2.10.2` it fails every time with:

Not sure if it's related, but you may try `<allowservicelogon>true</allowservicelogon>`.

**Comment by jakubgs** [comment]
Thanks for suggesting `<allowservicelogon>true</allowservicelogon>`. It appears to work, also in case of `2.10.2`. Appreciate it.
