### ISSUE TITLE
WMI is terrible

### ISSUE THREAD

**Issue by nxtn** [winsw/winsw#749]
Same as #204

Just found that 2.x completely doesn't work on my machine due to WMI failure. The 'Windows Management Instrumentation (Winmgmt)' service is running. Have tried to restart Windows. 3.x is working properly.

## Steps to reproduce

```console
> WinSW.exe /?
0000-00-00 00:00:00,000 FATAL - Unhandled exception
System.Management.ManagementException: Generic failure
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
System.Management.ManagementException: Generic failure
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```

## Environment

* WinSW version: 2.10.3/2.3.0
* WinSW package type: .NET 4.6.1/4.0
* Windows version: Windows 10, version 20H2

## Possible Solution

Switch to use native Win32 APIs like in 3.x.

**Comment by oleg-nenashev** [comment]
Works on my machine... But yes, it is a big deal.
Probably it is better to merge 2.x into 3.x and get the GA as soon as possible.
