### ISSUE TITLE
 Class winsw.Plugins.SharedDirectoryMapper.SharedDirectoryMapper does not exist

### ISSUE THREAD

**Issue by fbigun** [winsw/winsw#796]
**Summary**. 

start syncthing.exe

Error message for program startup
```
2021-02-25 19:04:56,600 INFO  - Starting syncthing
2021-02-25 19:04:56,614 ERROR - Failed to start service.
WinSW.Extensions.ExtensionException: mapNetworkDirs: Cannot load the class by name: winsw.Plugins.SharedDirectoryMapper.SharedDirectoryMapper
 ---> WinSW.Extensions.ExtensionException: mapNetworkDirs: Class winsw.Plugins.SharedDirectoryMapper.SharedDirectoryMapper does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtension(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.DoStart()
   at WinSW.WrapperService.OnStart(String[] args)
2021-02-25 19:04:57,649 FATAL - Failed to start the service.
```

```xml
  <extensions>
    <extension enabled="true" className="winsw.Plugins.SharedDirectoryMapper.SharedDirectoryMapper" id="mapNetworDirs">
      <mapping>
        <map enabled="false" label="N:" uncpath="\\UNC"/>
        <map enabled="false" label="M:" uncpath="\\UNC2"/>
      </mapping>
    </extension>
  </extensions>
```

## Environment

* WinSW version: v3.0.0-alpha.7
* WinSW package type: WinSW-x64.exe
* Windows version:  windows10 20H2

**Comment by juacamgo** [comment]
Hi @fbigun ,

I am facing the same issue using WinSW-x64.exe on Windows 10 Version 20H2 using WinSW v2.11.0, have you managed to solve the problem?

Thank you.

**Comment by fbigun** [comment]
> 嗨，@fbigun，
> 
> 我面临着同样的问题，使用WinSW-x64.exe在Windows 10版本20H2使用WinSW v2.11.0，你设法解决这个问题？
> 
> 谢谢。

no,this is bug

**Comment by karolmie1** [comment]
Do you guys know what is the last working version?

**Comment by mgaert** [comment]
Same issue

with the latest version WinWS 2.11! Is there any fix?

**Comment by karolmie1** [comment]
There are a few flavors that exist for each version. With one flavor I was successful, so maybe try all of them? The fattest binary was not working for me, one of the leaner ones did.

**Comment by ikihiki** [comment]
`className="WinSW.Plugins.RunawayProcessKillerExtension,WinSW.Plugins"` worked.
I think it is due to the fact that the assembly in which the pulgin exists is different in ILMerge and PublishSingleFile.
