### ISSUE TITLE
Service fails for any download exception 

### ISSUE THREAD

**Issue by cristianbojor** [winsw/winsw#814]
Hello, 

First, thank you for the great project!

It seems that for any download exception (_from_ not available), an aggregate exception is thrown, even if failOnError is false:

```
2021-03-26T09:11:22.478 ERROR service - Failed to download https://some-server/runner.bat to C:\Program Files (x86)\someprogram\program\runner2.bat
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'some-server'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WinSW.Download.<PerformAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'preprodupdate-preprod.smartcheck.solutions'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WinSW.Download.<PerformAsync>d__16.MoveNext()<---

2021-03-26T09:11:22.484 ERROR service - Failed to start service.
System.AggregateException: One or more errors occurred.
   at WinSW.WrapperService.DoStart()
   at WinSW.WrapperService.OnStart(String[] args)
```

I think the problem is at this line:
https://github.com/winsw/winsw/blob/3c5884e7b8a26691c0f3da722a69199a0f1f4d62/src/WinSW.Core/WrapperService.cs#L299
Maybe the exception should be thrown only if _exceptions_ is empty.

## Environment
WinSW version: 2.11.0 and WinSW v3.0.0-alpha.8
WinSW package type: .NET 4.6.1
Windows version: Windows 10

**Comment by sinjp** [comment]
Similar to #787, The service startup fails or hangs, despite `failOnError="false"`, when the server is unavailable. This was driving me crazy as it kills my "autoupdate" functionality until I saw these issues.

I think the new exception should be thrown only if exceptions is _not_ empty. The below 2 changes worked for me, but note the existing TODO would likely fix this issue.

```c#
catch (AggregateException e)
{
    var exceptions = new List<Exception>();  // 1) Remove fixed length
    for (int i = 0; i < tasks.Length; i++)
    {
        if (tasks[i].IsFaulted)
        {
            var download = downloads[i];
            string errorMessage = $"Failed to download {download.From} to {download.To}";
            var exception = tasks[i].Exception!;
            Log.Error(errorMessage, exception);
            // TODO: move this code into the download logic
            if (download.FailOnError)
            {
                exceptions.Add(new IOException(errorMessage, exception));
            }
        }
    }
    if (exceptions.Count != 0)  // 2) Confirm exceptions exist that should not be ignored
    {
        throw new AggregateException(exceptions);
    }
}
```

I also seemed to have trouble with service startup hanging, possibly due to `download.PerformAsync()` so a quick workaround is to add a timeout to `Task.WaitAll(tasks, 10000); // 10s blanket timeout` to ensure failure.
