### ISSUE TITLE
Winsw crashed leaving controlled executable running

### ISSUE THREAD

**Issue by tomqwpl** [winsw/winsw#842]
This is using WinSW version 3.0.0 alpha 9

I start my windows service, but then winsw crashes. Windows then thinks that the service isn't running. You try and restart the windows service but now that fails because my executable is actually still running and is listening on the port. Second instance tries to bind to the same port which then fails.

The only diagnostics I've been able to find so far is in the Windows event viewer:

```
Application: winsw.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at WinSW.AbstractFileLogAppender.SafeLogError(StreamReader errorReader)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Since this is an async request, you can't tell what the _real_ stack trace is, why the null reference has really occurred.

Any suggestions for diagnosis?

**Comment by tomqwpl** [comment]
I *think* this is caused by having a prestart command set, and having the stdout path and the stderr path for that pointing at the same file (I didn't intend to do that).
