### ISSUE TITLE
 Unable to register service

### ISSUE THREAD

**Issue by caexy** [winsw/winsw#851]
Unable to register service

.\winsw64.exe install

The configuration file could not be loaded. The '?' character, hexadecimal value 0xA0, cannot be included in a name. Line 13, position 15.
System.IO.InvalidDataException: The '?' character, hexadecimal value 0xA0, cannot be included in a name. Line 13, position 15.
 ---> System.Xml.XmlException: The '?' character, hexadecimal value 0xA0, cannot be included in a name. Line 13, position 15.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at WinSW.XmlServiceConfig..ctor(String path)
   --- End of inner exception stack trace ---
   at WinSW.XmlServiceConfig..ctor(String path)
   at WinSW.Program.LoadConfigAndInitLoggers(String path, Boolean inConsoleMode)
   at WinSW.Program.<>c__DisplayClass7_0.<Main>g__Install|1(String pathToConfig, Boolean noElevate, String username, String password)

If you need to attach your configuration, please do it pelow:

```xml
<service>
    <id>frp</id>
    <name>frp0.37.0-windows-amd64</name>
    <description>FRP client This service uses FRPC for Intranet penetration</description>
    <executable>D:\frp_0.37.0_windows_amd64\frpc.exe</executable>
    <arguments>-c frpc.ini</arguments>
    <onfailure action="restart" delay="60 sec"/>
    <onfailure action="restart" delay="120 sec"/>
    <logmode>append</logmode>
    <logpath>logs</logpath>
</service>
```

## Environment

* WinSW version: 2.11.0
* WinSW package type:  .NET 4
* Windows version: 20H2
* Wrapped executable and version: Latest release

**Comment by nxtn** [comment]
> The '?' character, hexadecimal value 0xA0, cannot be included in a name. Line 13, position 15.
