### ISSUE TITLE
roll-by-size-time does not roll by size

### ISSUE THREAD

**Issue by TheNobleGoblin** [winsw/winsw#894]
**Summary**. Within `RollingSizeTimeLogAppender.CopyStreamWithRotationAsync` the portion of code which handles rolling the log file by size fails to close the `FileStream` before attempting to move the file. This causes the roll to fail with an Event Log entry reading:
```
Failed to roll size time log: The process cannot access the file because it is being used by another process.
```

## Steps to reproduce

1. Use a small value for `<sizeThreshold>` with an application that logs enough to pass the threshold fairly quickly and an `<autoRollAtTime>` value set a few minutes in the future.
2. Watch the size of the log file and observe that it does not roll when the size exceeds the threshold. 
3. Observe the log file does roll at the set `<autoRollAtTime>`

My `<log>` configuration for testing. `<autoRollAtTime>` was usually set 5 minutes into the future.
```xml
<log mode="roll-by-size-time">
	<sizeThreshold>10</sizeThreshold>
	<pattern>yyyy-MM-dd</pattern>
	<autoRollAtTime>21:30:00</autoRollAtTime>
</log>
```

## Environment

* WinSW version: Tested both 2.9.0 and 2.10.3 expect it's still present in current v3
* Windows version: Windows 10 Home and Enterprise

## Possible Solution

After the `fileLength > this.SizeThreshold` check in `RollingSizeTimeLogAppender.CopyStreamWithRotationAsync` add a call to `writer.Dispose();` and consider moving the following lines outside the `try-catch` block:
```
// even if the log rotation fails, create a new one, or else
// we'll infinitely try to roll.
copy.Writer = writer = new FileStream(logFile, FileMode.Create);
fileLength = new FileInfo(logFile).Length;
```
possibly the same for those lines within the `<autoRollAtTime>` section. It can't create a new log when rotation fails if the failure is throwing an Exception.

I tested a build of 2.10.3 with the added call to `writer.Dispose();` built using the linked .NET 5 SDK from the contributing page and verified that the size and time rolling worked afterwards.

**Comment by TheNobleGoblin** [comment]
Noticed the missing `writer.Dispose();` is added as part of this PR from last year, just not finished and merged yet.

https://github.com/winsw/winsw/pull/564

**Comment by MarkoDju** [comment]
My service crashed/stopped working when using roll-by-size-time.
The error in windows event viewer was:
> Unhandled exception in task. System.ObjectDisposedException: Cannot access a closed file.
>    at System.IO.__Error.FileNotOpen()
>    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
>    at WinSW.StreamCopyOperation.<CopyLineAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at WinSW.RollingSizeTimeLogAppender.<CopyStreamWithRotationAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at WinSW.AbstractFileLogAppender.<SafeLogOutput>d__13.MoveNext()

The service weirdly was still showing as running in windows services, but actually was not doing anything. The log was rotated and a new log file created, but nothing was being logged. Restarting did not help (did not reboot the machine for other reasons), reinstalling the service did help.

Log configuration was as follows:

```
<log mode="roll-by-size-time">
	<sizeThreshold>10240</sizeThreshold>
	<pattern>yyyyMMdd</pattern>
	<autoRollAtTime>00:00:00</autoRollAtTime>
	<keepFiles>30</keepFiles>
</log>
```

I was using WinSW v3.0.0-alpha.10, .NET 4.6.1, On Windows Server 2008.

**Comment by thkuebler** [comment]
Hello,

we have the same problem by using the winsw version 2.11. The configuration looks like:

_<log mode="roll-by-size-time">
	<pattern>yyyyMMdd</pattern>
        <autoRollAtTime>00:00:00</autoRollAtTime>
       <zipOlderThanNumDays>5</zipOlderThanNumDays>
</log>_

with this configuration we got from time to time this exception in production,

Exception Info: System.ObjectDisposeException

at SystemJO._Error.FileNotOpen()
at SystemJO.FileStream.Write(byte[], Int32, Int32)
at WinSW.StreamCopyOperation.CopyLine()
at WinSW.RollingSizeTimeLogAppender.CopyStreamWithRotation(...)

process is terminate, but from the process view it seams to run, but we have to restart the service. The log files are very big.

Question: Could we deactivate the rolling function, we did not need this normaly.

**Comment by thkuebler** [comment]
the complete configuration:
`<log mode="roll-by-size-time">
     <pattern>yyyyMMdd</pattern>
     <autoRollAtTime>00:00:00</autoRollAtTime>
    <zipOlderThanNumDays>5</zipOlderThanNumDays>
</log>`

**Comment by viceice** [comment]
also `keepFiles` seems to not work with `roll-by-size-time`

**Comment by NuthanKishoreDev** [comment]
Any idea , when this issue will get resolved @TheNobleGoblin @viceice @thkuebler @MarkoDju @kohsuke ,
