### ISSUE TITLE
Log "Thread failed unexpectedly" errors as warnings

### ISSUE THREAD

**Issue by kenny-evitt** [winsw/winsw#94]
I just upgraded to version 1.17. I'm still having issues with my winsw service restarting after restarts triggered by (automatic) Windows Updates – see #52.

There seems to be new info being logged in the _wrapper.log_ file. Here's the contents pertaining to the recent failed shutdown (and subsequent failure to restart automatically):

```
2015-04-18 03:08:31 - Stopping recp-notes
2015-04-18 03:08:31 - ProcessKill 2812
2015-04-18 03:08:32 - Thread failed unexpectedly
Message:The interface is unknown
Stacktrace:   at System.Diagnostics.EventLog.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type)
   at winsw.WrapperService.LogEvent(String message, EventLogEntryType type)
   at winsw.WrapperService.<>c__DisplayClass4.<StartProcess>b__3()
   at winsw.WrapperService.<>c__DisplayClass1.<StartThread>b__0()
2015-04-18 03:08:32 - Shutdown exception
Message:A system shutdown is in progress. (Exception from HRESULT: 0x8007045B)
Stacktrace:   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
   at winsw.WrapperService.StopIt()
   at winsw.WrapperService.OnShutdown()
```

**Comment by oleg-nenashev** [comment]
This behavior is "as designed" in Windows, because it starts from terminating spawned processes and detaching management features. BTW, it makes sense to properly catch the exception and log it as a warning.

**Comment by kenny-evitt** [comment]
@oleg-nenashev thanks; I edited the title to reflect your comment.
