### ISSUE TITLE
java.lang.Exception: Failed to initialize GATicket

### ISSUE THREAD

**Issue by uchiha-pain** [winsw/winsw#954]
Hi! I am using winsw. I'm getting this error message
```
Exception in thread "async-dispatch-4" java.lang.Exception: Failed to initialize GATicket.
Failed to initialize TICKET_API error=80100007[[TCK_API_ERR_SERVER_COMM_FAILED]]
at com.gemplus.gemauth.api.GATicket.<init>(GATicket.java:143)
at pathpoint_ers_client.identity_agent$get_ticket.invokeStatic(identity_agent.clj:15)
at pathpoint_ers_client.identity_agent$get_ticket.invoke(identity_agent.clj:15)
at pathpoint_ers_client.client$fn__18711.invokeStatic(client.clj:153)
at pathpoint_ers_client.client$fn__18711.invoke(client.clj:152)
at clojure.lang.MultiFn.invoke(MultiFn.java:229)
at pathpoint_ers_client.client$process_frame$fn__18845$state_machine__6449__auto____18874$fn__18876.invoke(client.clj:184)
at pathpoint_ers_client.client$process_frame$fn__18845$state_machine__6449__auto____18874.invoke(client.clj:184)
at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
at pathpoint_ers_client.client$process_frame$fn__18845.invoke(client.clj:184)
at clojure.lang.AFn.run(AFn.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1191$fn__1192.invoke(concurrent.clj:29)
at clojure.lang.AFn.run(AFn.java:22)
at java.base/java.lang.Thread.run(Thread.java:833)
```
My xml file is as below
```
<service>
<id>pathpoint-ers-client-0.1.2-OpenMedical-Int-01-standalone</id>
<name>pathpoint-ers-client-0.1.2-OpenMedical-Int-01-standalone</name>
<description>This is the service for open Medical Pathpoint.</description>
<!--
<serviceaccount>
<username>DESKTOP-R90707F\alex</username>
<password>alex123456</password>
<allowservicelogon>true</allowservicelogon>
</serviceaccount>
<serviceaccount>
<username>LocalSystem</username>
</serviceaccount>
-->
<executable>java</executable>
<arguments>-jar "C:/Users/alex/client/pathpoint-ers-client-0.1.2-OpenMedical-Int-01-standalone.jar" 192.168.0.174</arguments>
<priority>abovenormal</priority>

<!--
<workingdirectory>C:/Users/OM-INT/client</workingdirectory>
-->
<log mode="append" />

<onfailure action="restart" delay="10 sec"/>
<onfailure action="restart" delay="20 sec"/>
</service>
```

**Comment by uchiha-pain** [comment]
I don't get this problem when I run this I think my problem could be resolved if I run this jar file C:/Users/alex/client/pathpoint-ers-client-0.1.2-OpenMedical-Int-01-standalone.jar as an administrator. Is their any way to run this file with admin privileges in winsw? I have tried LocalSystem but it is not working.
