### ISSUE TITLE
Service (postgresql) starts with backtrace, when stop, stops service (postgresql) but wrapper hangs with another backtrace

### ISSUE THREAD

**Issue by rubin55** [winsw/winsw#992]
**Summary**. Describe the expected and actual behavior here.
I've created a service XML to handle PostgreSQL 15. I downloaded the EDB 15.1 zip archive, I've created a postgres service account which I've configured the service to use. I can start the service normally, and logs indicate all is well except for a backtrace in the wrapper log. Then, a shutdown does actually shutdown postgres, but the wrapper.exe keeps running and the service shows as running in the service view of computer management. The log says:

```
C:\ProgramData\PostgreSQL\log>type postgresql-service.wrapper.log
2022-12-28 22:55:07,546 DEBUG - Starting WinSW in service mode
2022-12-28 22:55:07,632 INFO  - Starting C:\Program Files\PostgreSQL\pgsql15\bin\pg_ctl.exe  -D C:\ProgramData\PostgreSQL\data -l C:\ProgramData\PostgreSQL\log\postgresql.log start
2022-12-28 22:55:07,679 INFO  - Started process 10748
2022-12-28 22:55:07,679 DEBUG - Forwarding logs of the process System.Diagnostics.Process (pg_ctl) to WinSW.ResetLogAppender
2022-12-28 22:55:08,191 ERROR - Thread failed unexpectedly
WinSW.CommandException: Failed to open the service control manager database. Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at WinSW.Native.Throw.Command.Win32Exception(String message)
   at WinSW.Native.ServiceManager.Open(ServiceManagerAccess access)
   at WinSW.WrapperService.SignalStopped()
   at WinSW.WrapperService.<>c__DisplayClass31_0.<StartProcess>g__OnProcessCompleted|0(Process proc)
   at WinSW.Util.ProcessHelper.<>c__DisplayClass6_0.<StartThread>b__0()
2022-12-28 22:56:33,483 INFO  - Stopping postgresql
2022-12-28 22:56:33,514 INFO  - Started process 11172
2022-12-28 22:56:33,514 ERROR - Failed to stop service.
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at WinSW.WrapperService.DoStop()
   at WinSW.WrapperService.OnStop()
```

## Steps to reproduce
1. Download EDB Postgres 15.1 zip distribution, place on path
2. Create a service account `postgres`, not member of User group
3. create a database directory for this user, and set the aforementioned postgres user as owner
4. Then initdb the data directory as the postgres user
5. Place the service xml (see below) and install the service
6. Observe the service starts succesfully, look at the logs, might observe backtrace mentioned above
7. Try to shutdown the service. It fails, observe the wrapper.exe keeps running but postgres did shut down correctly?

If you need to attach your configuration, please do it pelow:

```xml
<service>
   <id>postgresql</id>
   <name>PostgreSQL Database</name>
   <description>PostgreSQL Database</description>
   <startmode>Manual</startmode>

   <!-- Below does not work, see https://github.com/winsw/winsw/issues/971 -->
   <!-- Manually configure username and password in service after install -->
   <serviceaccount>
     <username>postgres</username>
     <password>somepass</password>
     <allowservicelogon>true</allowservicelogon>
   </serviceaccount>

   <env name="POSTGRESQL_HOME" value="C:\Program Files\PostgreSQL\pgsql15"/>
   <env name="POSTGRESQL_DATA" value="C:\ProgramData\PostgreSQL\data"/>
   <env name="POSTGRESQL_LOGS" value="C:\ProgramData\PostgreSQL\log"/>

   <logpath>C:\ProgramData\PostgreSQL\log</logpath>
   <logmode>reset</logmode>

   <executable>%POSTGRESQL_HOME%\bin\pg_ctl.exe</executable>
   <startargument>-D</startargument>
   <startargument>%POSTGRESQL_DATA%</startargument>
   <startargument>-l</startargument>
   <startargument>%POSTGRESQL_LOGS%\postgresql.log</startargument>
   <startargument>start</startargument>

   <stopexecutable>%POSTGRESQL_HOME%\bin\pg_ctl.exe</stopexecutable>
   <stopargument>-D</stopargument>
   <stopargument>%POSTGRESQL_DATA%</stopargument>
   <stopargument>-l</stopargument>
   <stopargument>%POSTGRESQL_LOGS%</stopargument>
   <stopargument>stop</stopargument>

</service>
```

## Environment

* WinSW version: `v2.11`
* WinSW package type: `.NET 4.6.1`
* Windows version: `Windows 11 ARM64 (Surface Pro X)`
* Wrapped executable and version: `PostgreSQL 15.1 for Windows x64, provided bij EDB`

## Possible Solution

N/A.

**Comment by rubin55** [comment]
Note that the above seems to be specific to PostgreSQL; I've succesfully configured both Apache ActiveMQ Artemis and RabbitMQ with the exact-same setup. Might this have to do with the fact that `pg_ctl -D blah start` backgrounds?

**Comment by rubin55** [comment]
I managed indeed to work around this by not using pg_ctl to start the server, but `postgres` directly. So instead of `pg_ctl -D blah start`, you can do `postgres -D blah`. The latter runs postgres in foreground, but this is handled gracefully by winsw.
